apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: job-tracker
type: Opaque
stringData:
  # Keys required by the official postgres image
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: jobtracker
  # Same values, different key names -- required by our FastAPI backend code
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: jobtracker
