apiVersion: v1
kind: Pod
metadata:
  name: cm-test
  namespace: job-tracker
spec:
  containers:
    - name: cm-test
      image: busybox
      command: ["sh", "-c", "env; sleep 3600"]
      envFrom:
        - configMapRef:
            name: test-config
  restartPolicy: Never