apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  namespace: job-tracker
spec:
  containers:
    - name: pvc-test
      image: busybox
      command: ["sh", "-c", "echo hello-from-pvc > /data/test.txt; sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: test-vol
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: test-pvc